### PR TITLE
39 Change onMouseEnter and onMouseExit Behaviour to be more Intuitive

### PR DESCRIPTION
**Pull request by Gleethos**

### CODE REVIEW

**Comment by Gleethos** [comment]
After some thinking I have come to the conclusion that we should consider
also implementing the `onMouseEnterSurface` and `onMouseExiSurface` methods
how we initially envisioned the Swing behavior to be like instead of delegating directly 
to the underlying Swing enter/exit behavior.
I am not sure though how this could be done because we don't get any exit events
for children without enter/exit events.

**Comment by Gleethos** [comment]
Any ideas?

**Comment by Mazi-S** [comment]
So you suggest to have an `onMouseEnterSurface` / `onMouseExiSurface` that triggers enter on entering a component and exit on entering a child component. And unlike swing, you want to trigger the exit (on entering a child) regardless of whether the child has a listener attached?

I think this is only possible if you register a mouse listener on at least every direct child.
Alternatively, you can listen for all mouse move events and check for enter/exit. But I don't think we should do that.

**Comment by Mazi-S** [comment]
So you want to add the ability to specify the `UI.ComponentArea` when adding a listener?
```Java
.onMouseEnter(ComponentArea.BODY, (it) -> {})
```

If we want to support this, I would suggest implementing the mouse move events approach. Meaning, we listen for every mouse move event and check if we are entering / exiting a component.
The current implementation I have done relays on the swing enter/exit events which does not support this. So we will end up by implementing a second event system and process each move event twice.

I like the idea of supporting this, and my preferred solution would be to extend the swing event system to fit our needs. But I am afraid that is not possible.

**Comment by Gleethos** [comment]
> So you want to add the ability to specify the UI.ComponentArea when adding a listener?

Yes that is exactly the idea. I already pushed a commit which exposes the area shapes of a component.
Feel free to use that to perform the necessary area checks.

Yeah and I also see this only working with a motion listener.
But it should be possible to integrate this with the existing dispatcher,
so I don't know if we really need an additional class.
I quickly hacked together something which kinda seems to work for the most part,
although there are still some quirks here and there:

```diff --git a/src/main/java/swingtree/EnterExitComponentBoundsEventDispatcher.java b/src/main/java/swingtree/EnterExitComponentBoundsEventDispatcher.java
index 8f5df719..8081e7af 100644
--- a/src/main/java/swingtree/EnterExitComponentBoundsEventDispatcher.java
+++ b/src/main/java/swingtree/EnterExitComponentBoundsEventDispatcher.java
@@ -2,15 +2,15 @@ package swingtree;
 
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
+import swingtree.style.ComponentExtension;
 
+import javax.swing.JComponent;
 import java.awt.*;
 import java.awt.event.MouseAdapter;
 import java.awt.event.MouseEvent;
 import java.awt.event.MouseListener;
-import java.util.ArrayList;
 import java.util.List;
-import java.util.Map;
-import java.util.WeakHashMap;
+import java.util.*;
 
 /**
  *  A custom event dispatcher for mouse enter and exit events based on the mouse
@@ -27,30 +27,35 @@ final class EnterExitComponentBoundsEventDispatcher {
     private static final EnterExitComponentBoundsEventDispatcher eventDispatcher = new EnterExitComponentBoundsEventDispatcher();
     private static final MouseListener dispatcherListener = new MouseAdapter() { };
 
-    static void addMouseEnterListener(Component component, MouseListener listener) {
-        ComponentEnterExitListeners listeners = eventDispatcher.listeners.computeIfAbsent(component, k -> {
+    static void addMouseEnterListener(UI.ComponentArea area, Component component, MouseListener listener) {
+        Map<Component, ComponentEnterExitListeners> allListeners = eventDispatcher.listeners[area.ordinal()];
+        ComponentEnterExitListeners listeners = allListeners.computeIfAbsent(component, k -> {
             // ensures that mouse events are enabled
             k.addMouseListener(dispatcherListener);
-            return new ComponentEnterExitListeners();
+            return new ComponentEnterExitListeners(area, component);
         });
         listeners.addEnterListener(listener);
     }
 
-    static void addMouseExitListener(Component component, MouseListener listener) {
-        ComponentEnterExitListeners listeners = eventDispatcher.listeners.computeIfAbsent(component, k -> {
+    static void addMouseExitListener(UI.ComponentArea area, Component component, MouseListener listener) {
+        Map<Component, ComponentEnterExitListeners> allListeners = eventDispatcher.listeners[area.ordinal()];
+        ComponentEnterExitListeners listeners = allListeners.computeIfAbsent(component, k -> {
             // ensures that mouse events are enabled
             k.addMouseListener(dispatcherListener);
-            return new ComponentEnterExitListeners();
+            return new ComponentEnterExitListeners(area, component);
         });
         listeners.addExitListener(listener);
     }
 
 
-    private final Map<Component, ComponentEnterExitListeners> listeners;
+    private final Map<Component, ComponentEnterExitListeners>[] listeners;
 
     private EnterExitComponentBoundsEventDispatcher() {
-        listeners = new WeakHashMap<>();
+        listeners = new Map[UI.ComponentArea.values().length];
+        for (int i = 0; i < listeners.length; i++)
+            listeners[i] = new WeakHashMap<>();
         Toolkit.getDefaultToolkit().addAWTEventListener(this::onMouseEvent, AWTEvent.MOUSE_EVENT_MASK);
+        Toolkit.getDefaultToolkit().addAWTEventListener(this::onMouseEvent, AWTEvent.MOUSE_MOTION_EVENT_MASK);
     }
 
     public void onMouseEvent(AWTEvent event) {
@@ -59,11 +64,12 @@ final class EnterExitComponentBoundsEventDispatcher {
 
             Component c = mouseEvent.getComponent();
             while (c != null) {
-                ComponentEnterExitListeners componentListenerInfo = listeners.get(c);
-
-                if (componentListenerInfo != null)
-                    componentListenerInfo.dispatch(c, mouseEvent);
+                for ( Map<Component, ComponentEnterExitListeners> listeners : this.listeners ) {
+                    ComponentEnterExitListeners componentListenerInfo = listeners.get(c);
 
+                    if (componentListenerInfo != null)
+                        componentListenerInfo.dispatch(c, mouseEvent);
+                }
                 c = c.getParent();
             }
         }
@@ -75,14 +81,17 @@ final class EnterExitComponentBoundsEventDispatcher {
      *  bounds of the component or not.
      */
     private static class ComponentEnterExitListeners {
+
+        private final UI.ComponentArea area;
         private boolean isEntered;
         private final List<MouseListener> enterListeners;
         private final List<MouseListener> exitListeners;
 
-        public ComponentEnterExitListeners() {
-            isEntered = false;
-            enterListeners = new ArrayList<>();
-            exitListeners = new ArrayList<>();
+        public ComponentEnterExitListeners( UI.ComponentArea area, Component component ) {
+            this.area = area;
+            this.isEntered = false;
+            this.enterListeners = new ArrayList<>();
+            this.exitListeners  = new ArrayList<>();
         }
 
         public void addEnterListener(MouseListener listener) {
@@ -101,9 +110,9 @@ final class EnterExitComponentBoundsEventDispatcher {
                     if (isEntered)
                         return;
 
-                    onMouseEnter(component, event);
+                    boolean isInside = onMouseEnter(component, event);
 
-                    isEntered = true;
+                    isEntered = isInside;
                     break;
                 case MouseEvent.MOUSE_EXITED:
                     if (!isEntered)
@@ -112,17 +121,39 @@ final class EnterExitComponentBoundsEventDispatcher {
                     if (containsScreenLocation(component, event.getLocationOnScreen()))
                         return;
 
-                    onMouseExit(component, event);
+                    boolean isOutside = onMouseExit(component, event);
 
-                    isEntered = false;
+                    isEntered = !isOutside;
                     break;
+                case MouseEvent.MOUSE_MOVED:
+                    if ( this.area != UI.ComponentArea.ALL )
+                        mouseMoved(component, event);
+                break;
             }
         }
 
-        private void onMouseEnter(Component component, MouseEvent mouseEvent) {
+        private boolean onMouseEnter(Component component, MouseEvent mouseEvent) {
             if (enterListeners.isEmpty())
-                return;
+                return true;
+
+            if ( this.area == UI.ComponentArea.ALL ) {
+                dispatchEnterToAllListeners(component, mouseEvent);
+            } else {
+                Optional<Shape> componentArea = ComponentExtension.from((JComponent) component).getComponentArea(area);
+                if ( !componentArea.isPresent() ) {
+                    if ( this.area == UI.ComponentArea.BORDER )
+                        return true; // no border means nothing to enter or exit on
+                    else
+                        dispatchEnterToAllListeners(component, mouseEvent);
+                } else if ( componentArea.get().contains(mouseEvent.getPoint()) )
+                    dispatchEnterToAllListeners(component, mouseEvent);
+                else
+                    return false;
+            }
+            return true;
+        }
 
+        private void dispatchEnterToAllListeners(Component component, MouseEvent mouseEvent) {
             MouseEvent localMouseEvent = withNewSource(mouseEvent, component);
             for (MouseListener listener : enterListeners) {
                 try {
@@ -133,10 +164,28 @@ final class EnterExitComponentBoundsEventDispatcher {
             }
         }
 
-        private void onMouseExit(Component component, MouseEvent mouseEvent) {
+        private boolean onMouseExit(Component component, MouseEvent mouseEvent) {
             if (exitListeners.isEmpty())
-                return;
+                return true;
 
+            if ( this.area == UI.ComponentArea.ALL ) {
+                dispatchExitToAllListeners(component, mouseEvent);
+            } else {
+                Optional<Shape> componentArea = ComponentExtension.from((JComponent) component).getComponentArea(area);
+                if ( !componentArea.isPresent() ) {
+                    if ( this.area == UI.ComponentArea.BORDER )
+                        return true; // no border means nothing to enter or exit on
+                    else
+                        dispatchExitToAllListeners(component, mouseEvent);
+                } else if ( !componentArea.get().contains(mouseEvent.getPoint()) )
+                    dispatchExitToAllListeners(component, mouseEvent);
+                else
+                    return false;
+            }
+            return true;
+        }
+
+        private void dispatchExitToAllListeners(Component component, MouseEvent mouseEvent) {
             MouseEvent localMouseEvent = withNewSource(mouseEvent, component);
             for (MouseListener listener : exitListeners) {
                 try {
@@ -146,6 +195,18 @@ final class EnterExitComponentBoundsEventDispatcher {
                 }
             }
         }
+
+        public void mouseMoved(Component component, MouseEvent e) {
+            if ( isEntered ) {
+                boolean isOutside = onMouseExit(component, e);
+                if (isOutside)
+                    isEntered = false;
+            } {
+                boolean isInside = onMouseEnter(component, e);
+                if (isInside)
+                    isEntered = true;
+            }
+        }
     }
 
     private static boolean isRelated(Component parent, Component other) {
diff --git a/src/main/java/swingtree/UIForAnySwing.java b/src/main/java/swingtree/UIForAnySwing.java
index 7ff46ff7..76a51c3d 100644
--- a/src/main/java/swingtree/UIForAnySwing.java
+++ b/src/main/java/swingtree/UIForAnySwing.java
@@ -3508,6 +3508,11 @@ public abstract class UIForAnySwing<I, C extends JComponent> extends UIForAnythi
      * @return This very instance, which enables builder-style method chaining.
      */
     public final I onMouseEnter( Action<ComponentMouseEventDelegate<C>> onEnter ) {
+        NullUtil.nullArgCheck(onEnter, "onEnter", Action.class);
+        return onMouseEnter(UI.ComponentArea.ALL, onEnter);
+    }
+
+    public final I onMouseEnter( UI.ComponentArea area, Action<ComponentMouseEventDelegate<C>> onEnter ) {
         NullUtil.nullArgCheck(onEnter, "onEnter", Action.class);
         return _with( thisComponent -> {
                     WeakReference<@Nullable C> source = new WeakReference<>(thisComponent);
@@ -3518,7 +3523,7 @@ public abstract class UIForAnySwing<I, C extends JComponent> extends UIForAnythi
                                 _runInApp(() -> onEnter.accept(new ComponentMouseEventDelegate<>( localComponent, e )));
                         }
                     };
-                    EnterExitComponentBoundsEventDispatcher.addMouseEnterListener(thisComponent, listener);
+                    EnterExitComponentBoundsEventDispatcher.addMouseEnterListener(area, thisComponent, listener);
                 })
                 ._this();
     }
@@ -3533,6 +3538,11 @@ public abstract class UIForAnySwing<I, C extends JComponent> extends UIForAnythi
      * @return This very instance, which enables builder-style method chaining.
      */
     public final I onMouseExit( Action<ComponentMouseEventDelegate<C>> onExit ) {
+        NullUtil.nullArgCheck(onExit, "onExit", Action.class);
+        return onMouseExit(UI.ComponentArea.ALL, onExit);
+    }
+
+    public final I onMouseExit( UI.ComponentArea area, Action<ComponentMouseEventDelegate<C>> onExit ) {
         NullUtil.nullArgCheck(onExit, "onExit", Action.class);
         return _with( thisComponent -> {
                     WeakReference<@Nullable C> source = new WeakReference<>(thisComponent);
@@ -3543,7 +3553,7 @@ public abstract class UIForAnySwing<I, C extends JComponent> extends UIForAnythi
                                 _runInApp(() -> onExit.accept(new ComponentMouseEventDelegate<>( localComponent, e )));
                         }
                     };
-                    EnterExitComponentBoundsEventDispatcher.addMouseExitListener(thisComponent, listener);
+                    EnterExitComponentBoundsEventDispatcher.addMouseExitListener(area, thisComponent, listener);
                 })
                 ._this();
     }
```

You delved way deeper into the event dispatch mechanics and I do not feel terribly confident with my approach above.
So let me know if what I did there makes sense. Maybe we can use it as a basis.
I do not feel terribly confident with my approach.

**Comment by Gleethos** [comment]
I worked on my solution some more but did not push it because I don't know if you have local work on
this branch or not. I encountered a bug in the creation of custom events. More specifically, the 
mouse position is wrong when we dispatch an event which is originally from another source than
the target source. 
Here the updated patch, works pretty well know:
```diff --git a/src/main/java/swingtree/EnterExitComponentBoundsEventDispatcher.java b/src/main/java/swingtree/EnterExitComponentBoundsEventDispatcher.java
index 8f5df719..b7cd8952 100644
--- a/src/main/java/swingtree/EnterExitComponentBoundsEventDispatcher.java
+++ b/src/main/java/swingtree/EnterExitComponentBoundsEventDispatcher.java
@@ -2,15 +2,16 @@ package swingtree;
 
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
+import swingtree.style.ComponentExtension;
 
+import javax.swing.JComponent;
+import javax.swing.SwingUtilities;
 import java.awt.*;
 import java.awt.event.MouseAdapter;
 import java.awt.event.MouseEvent;
 import java.awt.event.MouseListener;
-import java.util.ArrayList;
 import java.util.List;
-import java.util.Map;
-import java.util.WeakHashMap;
+import java.util.*;
 
 /**
  *  A custom event dispatcher for mouse enter and exit events based on the mouse
@@ -27,30 +28,35 @@ final class EnterExitComponentBoundsEventDispatcher {
     private static final EnterExitComponentBoundsEventDispatcher eventDispatcher = new EnterExitComponentBoundsEventDispatcher();
     private static final MouseListener dispatcherListener = new MouseAdapter() { };
 
-    static void addMouseEnterListener(Component component, MouseListener listener) {
-        ComponentEnterExitListeners listeners = eventDispatcher.listeners.computeIfAbsent(component, k -> {
+    static void addMouseEnterListener(UI.ComponentArea area, Component component, MouseListener listener) {
+        Map<Component, ComponentEnterExitListeners> allListeners = eventDispatcher.listeners[area.ordinal()];
+        ComponentEnterExitListeners listeners = allListeners.computeIfAbsent(component, k -> {
             // ensures that mouse events are enabled
             k.addMouseListener(dispatcherListener);
-            return new ComponentEnterExitListeners();
+            return new ComponentEnterExitListeners(area, component);
         });
         listeners.addEnterListener(listener);
     }
 
-    static void addMouseExitListener(Component component, MouseListener listener) {
-        ComponentEnterExitListeners listeners = eventDispatcher.listeners.computeIfAbsent(component, k -> {
+    static void addMouseExitListener(UI.ComponentArea area, Component component, MouseListener listener) {
+        Map<Component, ComponentEnterExitListeners> allListeners = eventDispatcher.listeners[area.ordinal()];
+        ComponentEnterExitListeners listeners = allListeners.computeIfAbsent(component, k -> {
             // ensures that mouse events are enabled
             k.addMouseListener(dispatcherListener);
-            return new ComponentEnterExitListeners();
+            return new ComponentEnterExitListeners(area, component);
         });
         listeners.addExitListener(listener);
     }
 
 
-    private final Map<Component, ComponentEnterExitListeners> listeners;
+    private final Map<Component, ComponentEnterExitListeners>[] listeners;
 
     private EnterExitComponentBoundsEventDispatcher() {
-        listeners = new WeakHashMap<>();
+        listeners = new Map[UI.ComponentArea.values().length];
+        for (int i = 0; i < listeners.length; i++)
+            listeners[i] = new WeakHashMap<>();
         Toolkit.getDefaultToolkit().addAWTEventListener(this::onMouseEvent, AWTEvent.MOUSE_EVENT_MASK);
+        Toolkit.getDefaultToolkit().addAWTEventListener(this::onMouseEvent, AWTEvent.MOUSE_MOTION_EVENT_MASK);
     }
 
     public void onMouseEvent(AWTEvent event) {
@@ -59,11 +65,12 @@ final class EnterExitComponentBoundsEventDispatcher {
 
             Component c = mouseEvent.getComponent();
             while (c != null) {
-                ComponentEnterExitListeners componentListenerInfo = listeners.get(c);
-
-                if (componentListenerInfo != null)
-                    componentListenerInfo.dispatch(c, mouseEvent);
+                for ( Map<Component, ComponentEnterExitListeners> listeners : this.listeners ) {
+                    ComponentEnterExitListeners componentListenerInfo = listeners.get(c);
 
+                    if (componentListenerInfo != null)
+                        componentListenerInfo.dispatch(c, mouseEvent);
+                }
                 c = c.getParent();
             }
         }
@@ -75,14 +82,16 @@ final class EnterExitComponentBoundsEventDispatcher {
      *  bounds of the component or not.
      */
     private static class ComponentEnterExitListeners {
+        private final UI.ComponentArea area;
         private boolean isEntered;
         private final List<MouseListener> enterListeners;
         private final List<MouseListener> exitListeners;
 
-        public ComponentEnterExitListeners() {
-            isEntered = false;
-            enterListeners = new ArrayList<>();
-            exitListeners = new ArrayList<>();
+        public ComponentEnterExitListeners( UI.ComponentArea area, Component component ) {
+            this.area = area;
+            this.isEntered = false;
+            this.enterListeners = new ArrayList<>();
+            this.exitListeners  = new ArrayList<>();
         }
 
         public void addEnterListener(MouseListener listener) {
@@ -101,9 +110,9 @@ final class EnterExitComponentBoundsEventDispatcher {
                     if (isEntered)
                         return;
 
-                    onMouseEnter(component, event);
+                    boolean isInside = onMouseEnter(component, event);
 
-                    isEntered = true;
+                    isEntered = isInside;
                     break;
                 case MouseEvent.MOUSE_EXITED:
                     if (!isEntered)
@@ -112,40 +121,94 @@ final class EnterExitComponentBoundsEventDispatcher {
                     if (containsScreenLocation(component, event.getLocationOnScreen()))
                         return;
 
-                    onMouseExit(component, event);
+                    boolean isOutside = onMouseExit(component, event);
 
-                    isEntered = false;
+                    isEntered = !isOutside;
                     break;
+                case MouseEvent.MOUSE_MOVED:
+                    if ( this.area != UI.ComponentArea.ALL )
+                        mouseMoved(component, event);
+                break;
             }
         }
 
-        private void onMouseEnter(Component component, MouseEvent mouseEvent) {
+        private boolean onMouseEnter(Component component, MouseEvent mouseEvent) {
             if (enterListeners.isEmpty())
-                return;
+                return true;
 
-            MouseEvent localMouseEvent = withNewSource(mouseEvent, component);
+            mouseEvent = withNewSource(mouseEvent, component);
+
+            if ( this.area == UI.ComponentArea.ALL ) {
+                dispatchEnterToAllListeners(mouseEvent);
+            } else {
+                Optional<Shape> componentArea = ComponentExtension.from((JComponent) component).getComponentArea(area);
+                if ( !componentArea.isPresent() ) {
+                    if ( this.area == UI.ComponentArea.BORDER )
+                        return true; // no border means nothing to enter or exit on
+                    else
+                        dispatchEnterToAllListeners(mouseEvent);
+                } else if ( componentArea.get().contains(mouseEvent.getPoint()) )
+                    dispatchEnterToAllListeners(mouseEvent);
+                else
+                    return false;
+            }
+            return true;
+        }
+
+        private void dispatchEnterToAllListeners(MouseEvent mouseEvent) {
             for (MouseListener listener : enterListeners) {
                 try {
-                    listener.mouseEntered(localMouseEvent);
+                    listener.mouseEntered(mouseEvent);
                 } catch (Exception e) {
-                    log.error("Failed to process mouseEntered event {}. Error: {}", localMouseEvent, e.getMessage(), e);
+                    log.error("Failed to process mouseEntered event {}. Error: {}", mouseEvent, e.getMessage(), e);
                 }
             }
         }
 
-        private void onMouseExit(Component component, MouseEvent mouseEvent) {
+        private boolean onMouseExit(Component component, MouseEvent mouseEvent) {
             if (exitListeners.isEmpty())
-                return;
+                return true;
 
-            MouseEvent localMouseEvent = withNewSource(mouseEvent, component);
+            mouseEvent = withNewSource(mouseEvent, component);
+
+            if ( this.area == UI.ComponentArea.ALL ) {
+                dispatchExitToAllListeners(mouseEvent);
+            } else {
+                Optional<Shape> componentArea = ComponentExtension.from((JComponent) component).getComponentArea(area);
+                if ( !componentArea.isPresent() ) {
+                    if ( this.area == UI.ComponentArea.BORDER )
+                        return true; // no border means nothing to enter or exit on
+                    else
+                        dispatchExitToAllListeners(mouseEvent);
+                } else if ( !componentArea.get().contains(mouseEvent.getPoint()) )
+                    dispatchExitToAllListeners(mouseEvent);
+                else
+                    return false;
+            }
+            return true;
+        }
+
+        private void dispatchExitToAllListeners(MouseEvent mouseEvent) {
             for (MouseListener listener : exitListeners) {
                 try {
-                    listener.mouseExited(localMouseEvent);
+                    listener.mouseExited(mouseEvent);
                 } catch (Exception e) {
-                    log.error("Failed to process mouseExited event {}. Error: {}", localMouseEvent, e.getMessage(), e);
+                    log.error("Failed to process mouseExited event {}. Error: {}", mouseEvent, e.getMessage(), e);
                 }
             }
         }
+
+        public void mouseMoved(Component component, MouseEvent e) {
+            if ( isEntered ) {
+                boolean isOutside = onMouseExit(component, e);
+                if (isOutside)
+                    isEntered = false;
+            } {
+                boolean isInside = onMouseEnter(component, e);
+                if (isInside)
+                    isEntered = true;
+            }
+        }
     }
 
     private static boolean isRelated(Component parent, Component other) {
@@ -167,13 +230,20 @@ final class EnterExitComponentBoundsEventDispatcher {
     }
 
     private static MouseEvent withNewSource(MouseEvent event, Component newSource) {
+        if ( event.getSource() == newSource )
+            return event;
+
+        // We need to convert the mouse position to the new source's coordinate system
+        Point mousePositionRelativeToNewComponent = event.getPoint();
+        SwingUtilities.convertPointToScreen(mousePositionRelativeToNewComponent, (Component) event.getSource());
+        SwingUtilities.convertPointFromScreen(mousePositionRelativeToNewComponent, newSource);
         return new MouseEvent(
             newSource,
             event.getID(),
             event.getWhen(),
             event.getModifiersEx(),
-            event.getX(),
-            event.getY(),
+            mousePositionRelativeToNewComponent.x,
+            mousePositionRelativeToNewComponent.y,
             event.getClickCount(),
             event.isPopupTrigger(),
             event.getButton()
diff --git a/src/main/java/swingtree/UIForAnySwing.java b/src/main/java/swingtree/UIForAnySwing.java
index 7ff46ff7..76a51c3d 100644
--- a/src/main/java/swingtree/UIForAnySwing.java
+++ b/src/main/java/swingtree/UIForAnySwing.java
@@ -3508,6 +3508,11 @@ public abstract class UIForAnySwing<I, C extends JComponent> extends UIForAnythi
      * @return This very instance, which enables builder-style method chaining.
      */
     public final I onMouseEnter( Action<ComponentMouseEventDelegate<C>> onEnter ) {
+        NullUtil.nullArgCheck(onEnter, "onEnter", Action.class);
+        return onMouseEnter(UI.ComponentArea.ALL, onEnter);
+    }
+
+    public final I onMouseEnter( UI.ComponentArea area, Action<ComponentMouseEventDelegate<C>> onEnter ) {
         NullUtil.nullArgCheck(onEnter, "onEnter", Action.class);
         return _with( thisComponent -> {
                     WeakReference<@Nullable C> source = new WeakReference<>(thisComponent);
@@ -3518,7 +3523,7 @@ public abstract class UIForAnySwing<I, C extends JComponent> extends UIForAnythi
                                 _runInApp(() -> onEnter.accept(new ComponentMouseEventDelegate<>( localComponent, e )));
                         }
                     };
-                    EnterExitComponentBoundsEventDispatcher.addMouseEnterListener(thisComponent, listener);
+                    EnterExitComponentBoundsEventDispatcher.addMouseEnterListener(area, thisComponent, listener);
                 })
                 ._this();
     }
@@ -3533,6 +3538,11 @@ public abstract class UIForAnySwing<I, C extends JComponent> extends UIForAnythi
      * @return This very instance, which enables builder-style method chaining.
      */
     public final I onMouseExit( Action<ComponentMouseEventDelegate<C>> onExit ) {
+        NullUtil.nullArgCheck(onExit, "onExit", Action.class);
+        return onMouseExit(UI.ComponentArea.ALL, onExit);
+    }
+
+    public final I onMouseExit( UI.ComponentArea area, Action<ComponentMouseEventDelegate<C>> onExit ) {
         NullUtil.nullArgCheck(onExit, "onExit", Action.class);
         return _with( thisComponent -> {
                     WeakReference<@Nullable C> source = new WeakReference<>(thisComponent);
@@ -3543,7 +3553,7 @@ public abstract class UIForAnySwing<I, C extends JComponent> extends UIForAnythi
                                 _runInApp(() -> onExit.accept(new ComponentMouseEventDelegate<>( localComponent, e )));
                         }
                     };
-                    EnterExitComponentBoundsEventDispatcher.addMouseExitListener(thisComponent, listener);
+                    EnterExitComponentBoundsEventDispatcher.addMouseExitListener(area, thisComponent, listener);
                 })
                 ._this();
     }
```

---

More specifically, the bug is on the `withNewSource` method, here is how I fixed it:
```java
    private static MouseEvent withNewSource(MouseEvent event, Component newSource) {
        if ( event.getSource() == newSource )
            return event;

        // We need to convert the mouse position to the new source's coordinate system
        Point mousePositionRelativeToNewComponent = event.getPoint();
        SwingUtilities.convertPointToScreen(mousePositionRelativeToNewComponent, (Component) event.getSource());
        SwingUtilities.convertPointFromScreen(mousePositionRelativeToNewComponent, newSource);
        return new MouseEvent(
            newSource,
            event.getID(),
            event.getWhen(),
            event.getModifiersEx(),
            mousePositionRelativeToNewComponent.x,
            mousePositionRelativeToNewComponent.y,
            event.getClickCount(),
            event.isPopupTrigger(),
            event.getButton()
        );
    }
```

Here I calculate `mousePositionRelativeToNewComponent` so that the reported mouse
position is relative to the new source component. That is also what a user expects from a mouse event.
We should assert this sort of stuff in a unit test.

**Pull request merged**
